// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;
import java.util.concurrent.TimeUnit;

public class ContactTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    if(SetUp.Platform == 0) {
      System.setProperty("webdriver.chrome.driver", SetUp.chrome);
      driver = new ChromeDriver();
    }else{
      System.setProperty("webdriver.gecko.driver", SetUp.firefox);
      driver = new FirefoxDriver();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contact() throws InterruptedException{
    driver.get("https://www.wolframalpha.com/");
    driver.manage().deleteAllCookies();
    driver.manage().window().setSize(new Dimension(945, 1020));

    driver.findElement(By.cssSelector(".\\_1YuY2")).click();
    driver.findElement(By.cssSelector(".Ugj72")).click();
    driver.findElement(By.cssSelector(".\\_1BhbZ:nth-child(2) > .\\_1AqBm:nth-child(3) span > span")).click();
    driver.findElement(By.linkText("Contact us to ask questions")).click();
    driver.findElement(By.xpath("//input[@id='general-name']")).sendKeys("Duc");
    driver.findElement(By.xpath("//input[@id='general-email']")).sendKeys("abcxyz@gmail.com");
    driver.findElement(By.xpath("//textarea[@id='general-message']")).sendKeys("Some message should be sent to you. I am sorry because i am  learning software testing");
    //driver.findElement(By.name("CAPTCHA")).click();

    {
      WebDriverWait wait = new WebDriverWait(driver, 10000);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//input[@name=\'CAPTCHA\']")));
    }
    //String captchaVal = JOptionPane.showInputDialog("Please enter the captcha value:");
    System.out.println("DUC");
    TimeUnit.SECONDS.sleep(15);

    driver.findElement(By.xpath("//input[@id='general-agree']")).click();
    driver.findElement(By.cssSelector(".row:nth-child(15) .submit")).click();

    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    TimeUnit.SECONDS.sleep(5);
    assertEquals(driver.findElement(By.cssSelector("h2:nth-child(4)")).getText(), "Thanks for sending us a message!");
  }
}
