// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.*;
import java.util.concurrent.TimeUnit;

public class ExampleFunctionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    if(SetUp.Platform == 0) {
      System.setProperty("webdriver.chrome.driver", SetUp.chrome);
      driver = new ChromeDriver();
    }else{
      System.setProperty("webdriver.gecko.driver", SetUp.firefox);
      driver = new FirefoxDriver();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void exampleFunctions() {
    driver.get("https://www.wolframalpha.com/");
    driver.manage().deleteAllCookies();
    driver.manage().window().setSize(new Dimension(945, 1020));

    driver.findElement(By.xpath("//a[@id=\'examples\']")).click();
    driver.findElement(By.xpath("//div[@id=\'math\']/div[2]/div")).click();
    driver.findElement(By.cssSelector(".example-subpage-section:nth-child(1) > .block-wrap:nth-child(6) svg")).click();
    driver.findElement(By.xpath("//input[@value=\'125 + 375\']")).click();
    {
      String value = driver.findElement(By.xpath("//input[@value=\'125 + 375\']")).getAttribute("value");
      assertThat(value, is("125 + 375"));
    }
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    //driver.findElement(By.xpath("//div[@id=\'__next\']/div/div/main/div[2]/div/div/div/section/section[2]/div")).click();
    {
      By loadingImage = By.cssSelector("_3L0WC _1GgzZ _3f1Mz");
      WebDriverWait wait = new WebDriverWait(driver, 60);
      wait.until(ExpectedConditions.invisibilityOfElementLocated(loadingImage));
    }


    driver.findElement(By.xpath("//section[2]/div")).click();
    driver.findElement(By.xpath("//section[2]/ul/li[4]/button/span/span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_3PYW- > .zcwYl"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//button[@type=\'button\'])[12]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("(//button[@type=\'button\'])[15]")).click();
    assertThat(driver.findElement(By.xpath("(//button[@type=\'button\'])[15]")).getText(), is("500"));
  }
}

