// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.*;

public class ExtendedKeyboardTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    if(SetUp.Platform == 0) {
      System.setProperty("webdriver.chrome.driver", SetUp.chrome);
      driver = new ChromeDriver();
    }else{
      System.setProperty("webdriver.gecko.driver", SetUp.firefox);
      driver = new FirefoxDriver();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void extendedKeyboard() {
    driver.get("https://www.wolframalpha.com/");
    driver.manage().deleteAllCookies();
    driver.manage().window().setSize(new Dimension(945, 1020));

    driver.findElement(By.xpath("//div[@id=\'__next\']/div/div/div/div/div[2]/ul/li/button/span/span")).click();
    driver.findElement(By.cssSelector(".\\_2hVzI:nth-child(2) > .\\_1oLFT:nth-child(1) .\\_2ZoPo")).click();
//    {
//      WebElement element = driver.findElement(By.xpath("//button[@value=\'π\']"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
    driver.findElement(By.cssSelector(".\\_2hVzI:nth-child(2) > .\\_1oLFT:nth-child(2) .\\_2ZoPo")).click();
//    {
//      WebElement element = driver.findElement(By.xpath("//button[@value=\'°\']"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
    driver.findElement(By.cssSelector(".\\_2hVzI:nth-child(2) > .\\_1oLFT:nth-child(3) .\\_2ZoPo")).click();
//    {
//      WebElement element = driver.findElement(By.xpath("//button[@value=\'∞\']"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
    driver.findElement(By.cssSelector(".\\_2hVzI:nth-child(2) > .\\_1oLFT:nth-child(4) .\\_2ZoPo")).click();
//    {
//      WebElement element = driver.findElement(By.xpath("//button[@value=\'√\']"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
    driver.findElement(By.cssSelector(".\\_2hVzI:nth-child(2) > .\\_1oLFT:nth-child(5) .\\_2ZoPo")).click();
//    {
//      WebElement element = driver.findElement(By.xpath("//button[@value=\'∫\']"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
    driver.findElement(By.cssSelector(".\\_2hVzI:nth-child(2) > .\\_1oLFT:nth-child(6) .\\_2ZoPo")).click();
//    {
//      WebElement element = driver.findElement(By.xpath("//button[@value=\'∑\']"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
    driver.findElement(By.cssSelector(".\\_2hVzI:nth-child(2) > .\\_1oLFT:nth-child(7) .\\_2ZoPo")).click();
//    {
//      WebElement element = driver.findElement(By.xpath("//button[@value=\'∂\']"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
    driver.findElement(By.cssSelector(".\\_2hVzI:nth-child(2) > .\\_1oLFT:nth-child(8) .\\_2ZoPo")).click();
    {
      String value =  driver.findElement(By.xpath("//div[@id='__next']/div/div/div/div/div/section/form/div/div/input")).getAttribute("value");
      assertEquals(8,value.length());
    }
  }
}
