// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.*;
import java.util.concurrent.TimeUnit;

public class PayForProTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    if(SetUp.Platform == 0) {
      System.setProperty("webdriver.chrome.driver", SetUp.chrome);
      driver = new ChromeDriver();
    }else{
      System.setProperty("webdriver.gecko.driver", SetUp.firefox);
      driver = new FirefoxDriver();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void payForPro() {
    driver.get("https://www.wolframalpha.com/");
    driver.manage().deleteAllCookies();
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    driver.findElement(By.cssSelector(".\\_1acfl:nth-child(4) span > span")).click();
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

    driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys("leson.tpc@gmail.com");
    driver.findElement(By.xpath("//input[@id=\'email\']")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys("12345678");
    driver.findElement(By.xpath("//button[@id=\'sign-in-btn\']")).click();

    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'menuOpener\']/span/span")).click();
    driver.findElement(By.xpath("//li[2]/section/ul/li/a/span/span")).click();
    driver.findElement(By.xpath("//div[2]/div/a/span")).click();
    js.executeScript("window.scrollTo(0,1000)");
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

    assertThat(driver.findElement(By.xpath("//div[@id='mini-cart-contents']/div[2]/div[2]/div[3]")).getText(), is("$57.00"));
    assertThat(driver.findElement(By.xpath("//div[@id='card-info']/h3")).getText(), is("Payment method"));
    assertThat(driver.findElement(By.xpath("//form[@id='form-page']/div/h3")).getText(), is("Student eligibility"));
    assertThat(driver.getTitle(), is("Checkout"));
  }
}
