// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.*;
import java.util.concurrent.TimeUnit;


public class RandomFunctionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private final int time = 10;
  @Before
  public void setUp() {
    if(SetUp.Platform == 0) {
      System.setProperty("webdriver.chrome.driver", SetUp.chrome);
      driver = new ChromeDriver();
    }else{
      System.setProperty("webdriver.gecko.driver", SetUp.firefox);
      driver = new FirefoxDriver();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void randomFunctions() {
    driver.get("https://www.wolframalpha.com/");
    driver.manage().deleteAllCookies();
    driver.manage().window().setSize(new Dimension(945, 1020));

    driver.findElement(By.id("random")).click();
    driver.findElement(By.cssSelector(".\\_2oXzi")).click();
    vars.put("function1", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));


    driver.manage().timeouts().implicitlyWait(time, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'random\']/span/span")).click();
    driver.findElement(By.cssSelector(".\\_2oXzi")).click();
    vars.put("function2", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));

    driver.manage().timeouts().implicitlyWait(time, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'random\']/span/span")).click();
    driver.findElement(By.cssSelector(".\\_2oXzi")).click();
    vars.put("function3", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));

    driver.manage().timeouts().implicitlyWait(time, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'random\']/span/span")).click();
    driver.findElement(By.cssSelector(".\\_2oXzi")).click();
    vars.put("function4", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));

    driver.manage().timeouts().implicitlyWait(time, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'random\']/span/span")).click();
    driver.findElement(By.cssSelector(".\\_2oXzi")).click();
    vars.put("function5", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));

    driver.manage().timeouts().implicitlyWait(time, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'random\']/span/span")).click();
    driver.findElement(By.cssSelector(".\\_2oXzi")).click();
    vars.put("function6", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));

    driver.manage().timeouts().implicitlyWait(time, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'random\']/span/span")).click();
    driver.findElement(By.cssSelector(".\\_2oXzi")).click();
    vars.put("function7", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));

    driver.manage().timeouts().implicitlyWait(time, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'random\']/span/span")).click();
    driver.findElement(By.cssSelector(".\\_2oXzi")).click();
    vars.put("function7", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));

    driver.manage().timeouts().implicitlyWait(time, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'random\']/span/span")).click();
    vars.put("function8", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));

    driver.manage().timeouts().implicitlyWait(time, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'random\']/span/span")).click();
    driver.findElement(By.cssSelector(".\\_2oXzi")).click();
    vars.put("function9", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));

    driver.manage().timeouts().implicitlyWait(time, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//button[@id=\'random\']/span/span")).click();
    driver.findElement(By.cssSelector(".\\_2oXzi")).click();
    vars.put("function10", driver.findElement(By.cssSelector(".\\_2oXzi")).getAttribute("value"));

    Set<String> set = new HashSet<>();
    for(Object it : vars.values()) set.add(it.toString());
    assertTrue(set.size()>1);
  }
}
