// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class SearchBarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    if(SetUp.Platform == 0) {
      System.setProperty("webdriver.chrome.driver", SetUp.chrome);
      driver = new ChromeDriver();
    }else{
      System.setProperty("webdriver.gecko.driver", SetUp.firefox);
      driver = new FirefoxDriver();
    }

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchBar() {
    driver.get("https://www.wolframalpha.com/");
    driver.manage().deleteAllCookies();
    driver.manage().window().setSize(new Dimension(945, 1020));

    driver.findElement(By.cssSelector(".\\_2oXzi")).sendKeys("x^2+5x+6");
    driver.findElement(By.cssSelector(".\\_2oXzi")).sendKeys(Keys.ENTER);

    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".\\_2z545:nth-child(1) > .Y4YRs")));
    }
    driver.findElement(By.cssSelector(".\\_2z545:nth-child(1) > .\\_124pH")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_1Qrw-:nth-child(1) > .\\_3fnRK"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//div[@id='__next']/div/div/main/div[2]/div/div/div/section/section/div")).click();
    driver.findElement(By.cssSelector(".\\_1oLFT:nth-child(3) .\\_1B-y0 > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_3PYW-"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_2TUsz:nth-child(2) .\\_10um4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_2TUsz:nth-child(2) .\\_10um4")).click();
    assertThat(driver.findElement(By.cssSelector(".\\_2TUsz:nth-child(2) .\\_10um4")).getText(), is("x^2 + 5 x + 6"));
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_16RX_"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_2XRvV"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,896)");
    driver.findElement(By.cssSelector(".\\_2z545:nth-child(12) > .\\_124pH")).click();
    driver.findElement(By.cssSelector(".\\_1oLFT:nth-child(3) > .\\_3OEvq > .\\_1B-y0 > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_3PYW-"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_2POPu:nth-child(2) > .\\_10um4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,781)");
    driver.findElement(By.cssSelector(".\\_2TUsz:nth-child(5) .\\_10um4")).click();
    assertThat(driver.findElement(By.xpath("//div[@id='__next']/div/div/main/div[2]/div/div/div/section/section[9]/div[4]/div/button")).getText(), is("x == -3 || x == -2"));
  }
}
