// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class SignInOutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver",URL.chrome);
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void signInOut() {
    driver.get("https://www.wolframalpha.com/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    vars.put("window_handle", driver.getWindowHandle());
    driver.findElement(By.xpath("(//button[@id=\'menuOpener\']/span/span)[3]")).click();

    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    driver.findElement(By.xpath("//div[@id=\'wolfram-id\']/input")).click();
    driver.findElement(By.xpath("//div[@id=\'wolfram-id\']/input")).sendKeys("leson.tpc@gmail.com");
    driver.findElement(By.xpath("//div[@id=\'form-actions\']/button")).click();
    driver.findElement(By.xpath("//div[@id=\'pw\']/input")).sendKeys("12345678");
    driver.findElement(By.xpath("//div[@id=\'remember\']/label")).click();
    driver.findElement(By.xpath("//div[@id=\'remember\']/label/input")).click();
    driver.findElement(By.xpath("//div[@id=\'form-actions\']/button")).click();

    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'__next\']/div/div/div/section/section[4]/h2/a/span/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    assertThat(driver.findElement(By.xpath("(//button[@id=\'menuOpener\']/span)[3]")).getText(), is("leson.tpc@gmail.co..."));
    driver.findElement(By.cssSelector(".oCnM3:nth-child(3)")).click();
    driver.findElement(By.xpath("//li[6]/a/span/span")).click();

    assertThat(driver.findElement(By.xpath("//p[contains(.,\'Plan: Basic\')]")).getText(), is("Plan: Basic"));
    driver.findElement(By.xpath("//div[@id=\'user-actions\']/div/a")).click();
    driver.findElement(By.xpath("//div[@id=\'form-main\']/h3")).click();
    assertThat(driver.getTitle(), is("Sign In - Wolfram"));
  }
}
